auto_start_break: true
auto_start_work: true
dark_theme: true
long_break_interval: 4
long_break_mins: 1
long_break_msg: focus on something else
notify: true
session_cmd: ""
short_break_mins: 5
short_break_msg: Take a breather
# sound: "playground"
sound_on_break: false
work_mins: 1
work_msg: Focus on your task
