vim.g.use_nerd_icons = true
if vim.fn.has("linux") == true then
    return {
        kind = {
            Text = "",
            Method = "m",
            Function = "",
            Constructor = "",
            Field = "",
            Variable = "",
            Class = "",
            Interface = "",
            Module = "",
            Property = "",
            Unit = "",
            Value = "",
            Enum = "",
            Keyword = "",
            Snippet = "",
            Color = "",
            File = "",
            Reference = "",
            Folder = "",
            EnumMember = "",
            Constant = "",
            Struct = "",
            Event = "",
            Operator = "",
            TypeParameter = "",
        },
        type = {
            Array = "",
            Number = "",
            String = "",
            Boolean = "蘒",
            Object = "",
        },
        documents = {
            File = "",
            Files = "",
            Folder = "",
            OpenFolder = "",
        },
        git = {
            Add = "",
            Mod = "",
            Remove = "",
            Ignore = "",
            Rename = "",
            Diff = "",
            Repo = "",
            Octoface = "",
        },
        ui = {
            ArrowClosed = "",
            ArrowOpen = "",
            Lock = "",
            Circle = "",
            BigCircle = "",
            BigUnfilledCircle = "",
            Close = "",
            NewFile = "",
            Search = "",
            Lightbulb = "",
            Project = "",
            Dashboard = "",
            History = "",
            Comment = "",
            Bug = "",
            Code = " ",
            Telescope = "",
            Gear = "",
            Package = "",
            List = "",
            SignIn = "",
            SignOut = "",
            Check = "",
            Fire = "",
            Note = "",
            BookMark = "",
            Pencil = "",
            ChevronRight = "",
            Table = "",
            Calendar = "",
            CloudDownload = "",
        },
        diagnostics = {
            Error = "",
            Warning = "",
            Information = "",
            Question = "",
            Hint = "",
        },
        misc = {
            Robot = "ﮧ",
            Squirrel = "",
            Tag = "",
            Watch = "",
            Smiley = "ﲃ",
            Package = "",
        },
    }
else
    --   פּ ﯟ   蘒練 some other good icons
    return {
        kind = {
            Text = " ",
            Method = " ",
            Function = " ",
            Constructor = " ",
            Field = " ",
            Variable = " ",
            Class = " ",
            Interface = " ",
            Module = " ",
            Property = " ",
            Unit = " ",
            Value = " ",
            Enum = " ",
            Keyword = " ",
            Snippet = " ",
            Color = " ",
            File = " ",
            Reference = " ",
            Folder = " ",
            EnumMember = " ",
            Constant = " ",
            Struct = " ",
            Event = " ",
            Operator = " ",
            TypeParameter = " ",
            Misc = " ",
        },
        type = {
            Array = " ",
            Number = " ",
            String = " ",
            Boolean = " ",
            Object = " ",
        },
        documents = {
            File = " ",
            Files = " ",
            Folder = " ",
            OpenFolder = " ",
        },
        git = {
            Add = " ",
            Mod = " ",
            Remove = " ",
            Ignore = " ",
            Rename = " ",
            Diff = " ",
            Repo = " ",
            Octoface = " ",
        },
        ui = {
            ArrowClosed = "",
            ArrowOpen = "",
            Lock = " ",
            Circle = " ",
            BigCircle = " ",
            BigUnfilledCircle = " ",
            Close = " ",
            NewFile = " ",
            Search = " ",
            Lightbulb = " ",
            Project = " ",
            Dashboard = " ",
            History = " ",
            Comment = " ",
            Bug = " ",
            Code = " ",
            Telescope = " ",
            Gear = " ",
            Package = " ",
            List = " ",
            SignIn = " ",
            SignOut = " ",
            NoteBook = " ",
            Check = " ",
            Fire = " ",
            Note = " ",
            BookMark = " ",
            Pencil = " ",
            ChevronRight = "",
            Table = " ",
            Calendar = " ",
            CloudDownload = " ",
        },
        diagnostics = {
            Error = " ",
            Warning = " ",
            Information = " ",
            Question = " ",
            Hint = " ",
        },
        misc = {
            Robot = " ",
            Squirrel = " ",
            Tag = " ",
            Watch = " ",
            Smiley = " ",
            Package = " ",
        },
    }
end
